routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['as' => 'front.'], function() {
    Route::get('manager/index', 'Front\ManagerController@index')->name('manager.index');
    Route::get('manager/order/{order}', 'Front\ManagerController@order')->name('manager.order');
    Route::post('manager/order/{order}', 'Front\ManagerController@updateOrder')->name('manager.update-order');
});

app/Cartridge.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Cartridge extends Model
{
    protected $table = 'order_cartridges';
    protected $fillable = ['type'];
    public $timestamps = false;

    const TYPE_CANON_CNB = 'cnb';
    const TYPE_CANON_CNBXL = 'cnbxl';

    const TYPE_HP_HPR = 'hpr';
    const TYPE_HP_HPB = 'hpb';
    const TYPE_HP_HPG = 'hpg';
    const TYPE_HP_HPP = 'hpp';

    public static $prices = [
        Order::ARTIKUL_HP => [
            self::TYPE_HP_HPR => 390,
            self::TYPE_HP_HPB => 391,
            self::TYPE_HP_HPG => 392,
            self::TYPE_HP_HPP => 393,
        ],
        Order::ARTIKUL_CANON => [
            self::TYPE_CANON_CNB => 390,
            self::TYPE_CANON_CNBXL => 490,
        ],
        Order::ARTIKUL_XEROX => [
        ],
    ];

    public function order()
    {
        return $this->belongsTo(Order::class, 'order_id', 'id');
    }
}

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    protected $fillable = ['fio', 'phone', 'article', 'sum', 'status'];

    const STATUS_NEW = 1;
    const STATUS_MANAGER = 2;
    const STATUS_COURIER = 3;
    const STATUS_DELIVERED = 4;
    const STATUS_DENIED = 5;

    public static $statuses = [
        self::STATUS_NEW, self::STATUS_MANAGER, self::STATUS_COURIER,
        self::STATUS_DELIVERED, self::STATUS_DENIED
    ];
    public static $statuses_translations = [
        self::STATUS_NEW => 'Новый',
        self::STATUS_MANAGER => 'Позвонил менеджер',
        self::STATUS_COURIER => 'Доставка курьером',
        self::STATUS_DELIVERED => 'Доставлено',
        self::STATUS_DENIED => 'Клиент отказался',
    ];

    const ARTIKUL_HP = 'hp';
    const ARTIKUL_CANON = 'canon';
    const ARTIKUL_XEROX = 'xerox';

    public static $articles = [
        self::ARTIKUL_HP, self::ARTIKUL_CANON, self::ARTIKUL_XEROX
    ];

    public static $prices = [
        self::ARTIKUL_CANON => 1000,
        self::ARTIKUL_HP => 2000,
        self::ARTIKUL_XEROX => 3000,
    ];

    public function cartridges()
    {
        return $this->hasMany(Cartridge::class, 'order_id', 'id');
    }

    public function getStatusHumanAttribute()
    {
        if (isset(self::$statuses_translations[$this->status])) {
            return self::$statuses_translations[$this->status];
        }
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Api/OrderController.php
<?php

namespace App\Http\Controllers\Api;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\Api\OrderCreateRequest;
use App\Order;
use App\Cartridge;
use App\Helpers\PhoneHelper;

class OrderController extends Controller
{
    public function create(OrderCreateRequest $request)
    {
        $printerPrice = Order::$prices[$request->article];
        $cartridgesTotalPrice = $request->sum - $printerPrice;
        if ($cartridgesTotalPrice < 0) {
            return response()->json([
                'id' => -1
            ]);
        }
        $cartridges = [];
        if ($cartridgesTotalPrice > 0) {
            $cartridgePrices = Cartridge::$prices[$request->article];
            foreach ($cartridgePrices as $type => $price) {
                if ($price <= $cartridgesTotalPrice && $cartridgesTotalPrice > 0) {
                    $cartridges[] = $type;
                    $cartridgesTotalPrice -= $price;
                }
            }
            if ($cartridgesTotalPrice != 0) {
                return response()->json([
                    'id' => -1
                ]);
            }
        }

        $data = $request->all();
        $data['status'] = Order::STATUS_NEW;
        $data['phone'] = (new PhoneHelper($data['phone']))->clean();
        $order = Order::create($data);
        foreach ($cartridges as $type) {
            $order->cartridges()->save(new Cartridge(['type' => $type]));
        }
        return response()->json([
            'id' => $order->id
        ]);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/Front/ManagerController.php
<?php

namespace App\Http\Controllers\Front;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Order;
use App\Http\Requests\Front\OrderUpdateRequest;

class ManagerController extends Controller
{
    public function index()
    {
        $orders = Order::latest()->paginate(10);
        return view('front.manager.orders', compact('orders'));
    }

    public function order(Order $order)
    {
        return view('front.manager.order-modal', compact('order'));
    }

    public function updateOrder(OrderUpdateRequest $request, Order $order)
    {
        $order->fill($request->only(['status', 'fio', 'phone']));
        $order->save();
        $orders = Order::latest()->paginate(10);
        return view('front.manager.orders-table', compact('orders'));
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/front/manager/order-modal.blade.php
<form method="POST" action="{{ route("front.manager.update-order", ["order" => $order]) }}">
    {{ csrf_field() }}
    <div class="form-group">
        <label for="fio">ФИО:</label>
        <input type="text" class="form-control" id="fio" name="fio" value="{{ $order->fio }}">
        <span class="help-block has-error"></span>
    </div>
    <div class="form-group">
        <label for="phone">Телефон:</label>
        <input type="text" class="form-control" id="phone" name="phone" value="{{ $order->phone }}">
        <span class="help-block has-error"></span>
    </div>
    <div class="form-group">
        <label for="phone">Статус:</label>
        <select name="status" class="form-control">
            @foreach (\App\Order::$statuses_translations as $id => $title)
                <option value="{{ $id }}" {{ $id == $order->status ? "selected" : "" }}>
                    {{ $title }}
                </option>
            @endforeach
        </select>
        <span class="help-block has-error"></span>
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-info">Сохранить</button>
    <div>
</form>

resources/views/front/manager/orders-table.blade.php
@foreach ($orders as $order)
    <tr>
        <td>{{ $order->id }}</td>
        <td>{{ $order->phone }}</td>
        <td>{{ $order->fio }}</td>
        <td>{{ $order->status_human }}</td>
        <td>
            @foreach ($order->cartridges as $cartridge)
                {{ $cartridge->type }}
            @endforeach
        </td>
        <td>{{ $order->sum }}</td>
        <td>
            <button class='btn btn-default btn--edit' data-id='{{ $order->id }}'>
                Редактировать
            </button>
        </td>
    </tr>
@endforeach
{{ $orders->links() }}
<div id="orders-page" data-page="{{ $orders->currentPage() }}"></div>

resources/views/front/manager/orders.blade.php
@extends('layouts.app')

@section('content')
    <table class='table table-hover table-bordered' id='orders'>
        <thead>
            <tr>
                <th>ID</th>
                <th>Телефон</th>
                <th>ФИО</th>
                <th>Статус</th>
                <th>Корзина</th>
                <th>Сумма</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @include('front.manager.orders-table', ['orders' => $orders])
        </tbody>
    </table>


    <div id="modal-order-edit" class="modal fade" role="dialog">
        <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">Редактирование</h4>
          </div>
          <div class="modal-body">
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
          </div>
        </div>
        </div>
    </div>

@endsection

@section('js')
<script>
    $('#orders').on('click', '.btn--edit', function(e) {
        e.preventDefault();
        var modal = $('#modal-order-edit');
        $.get("/manager/order/" + $(this).data('id'))
            .done(function(response) {
                modal.modal('show');
                modal.find('.modal-body').html(response);
            });
    });
    $('#modal-order-edit').on('submit', 'form', function(e) {
        e.preventDefault();
        var form = $(this);
        var data = form.serialize();
        var url = form.attr('action');
        form.find('.form-group.has-error').removeClass('has-error');
        form.find('.has-error').text('');
        var page = $('#orders-page').data('page');
        $.ajax({
            method: 'POST',
            url: url + '?page=' + page,
            data: data,
            success: function(response) {
                $('#orders').find('tbody').html(response);
                $('#modal-order-edit').modal('hide');
            },
            error: function(response) {
                var json = response && response.responseJSON;
                if (json && json.errors) {
                    $.each(json.errors, function(index, item) {
                        form.find('[name=' + index + ']')
                            .next('.has-error')
                            .text(item[0])
                            .closest('.form-group')
                            .addClass('has-error');
                    });
                }
            }
        });
    });
</script>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse" aria-expanded="false">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @guest
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>


    <!-- Optional theme -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    @yield('js')
</body>
</html>